services:
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data/db:/data/db
# Look into orchestration soon
# bind mount the mongodb path
    mlworker:
        build:
            context: ./ml-worker
            dockerfile: ../dockerfiles/mlworker.dev.dockerfile
        ports:
            - "8000:8000"
    backend:
        build:
            context: ./backend
            dockerfile: ../dockerfiles/backend.dockerfile
        ports:
            - "8080:8080"
        environment:
            - MONGODB_URI=mongodb://mongo:27017/backend
            - PYTHON_ML_SERVICE_URI=http://mlworker:8000
        depends_on:
            - mongo
            - mlworker
    frontend:
        build:
            context: ./frontend
            dockerfile: ../dockerfiles/frontend.dev.dockerfile
        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env
        environment:
            - BACKEND_PATH=http://backend:8080
        depends_on:
           - backend
        volumes:
            - ./frontend/src:/app/src
            - ./frontend/public:/app/public
