# service
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # TODO: placeholder image - replace when actually hasdeployed image to registry like dockerhub
        image: frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_PATH
          # cluster internal path or replace with actual IP
          value: http://backend.default:8080