services:
    # TODO: Keep this for testing, later use Atlas
    mongo:
        image: mongo:latest
# Look into orchestration soon
#    mlworker:
#        build:
#            context: ./ml-worker
#            dockerfile: Dockerfile
#        ports:
#            - "8000:8000"
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - MONGODB_URI=mongodb://mongo/backend
            - PYTHON_ML_SERVICE_URI=http://localhost:8000
        depends_on:
            - mongo
#           - mlworker
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env
        environment:
            - BACKEND_PATH=http://backend:8080
        #depends_on:
        #    - backend
        volumes:
            - /src:/app/src
            - /public:/app/public
